name: Deploy Dev github com action
on:
  push:
    branches:
      - dev
  # pull_request:
  #  branches:
  #    - dev

jobs:
  build:
    name: Deploy-dev para servidor trail
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do repositorio
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Deploy para pasta de teste
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-avzr" # ARGS: "-rltgoDzvO" #ARGS: "-avzr"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET_TESTE }}
        EXCLUDE: "/arquivos/, /assets/, /b/, /boletos/, /cielo/, /condicoes_gerais/, /email/, /imagens/, /inc/barcode-master/, /inc/boletos/, /inc/codigobarras/, /inc/comprovantes/, /inc/febraban-master/, /inc/guia_encaminhamento/, /inc/guia_recibo_faturamento/, /inc/img_carne/, /inc/openboleto-master/, /inc/PHPExcel/, /inc/PHPExcel_/, /integracao/, /scripts/, /site/, /.htaccess/, /.git/"